enableRobotsTXT: true
languageCode: es
params:
  contact:
    enable: true
    title: Contáctenos
  animate: true
  color:
    textColor: "#17202a"
    secondaryTextColor: "#17202a"
    textLinkColor: "#17202a"
    backgroundColor: "#8a9a5b"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#f0dfc8"
    secondaryColor: "#f8f9fa"
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: https://github.com/gurusabarish/hugo-profile
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com
  cloudinary_cloud_name: dny1bgulo
  listPages:
    disableFeaturedImage: false
  useBootstrapCDN: false
  terms:
    read: Read
    toc: Table Of Contents
    copyright: Todos los derechos reservados
    pageNotFound: Page not found
    emailText: Check out this site
  education:
    enable: false
    index: false
    items:
      - title: Master of Business Administration
        school:
          name: University of California, Berkeley
          url: https://example.org
        date: 2013 - 2015
        GPA: 3.8 out of 5.0
        content: >-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: Bachelor of Science in Computer Science
        school:
          name: Massachusetts Institute of Technology
          url: https://example.org
        date: 2009 - 2013
        GPA: 3.9 out of 5.0
        content: >-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial
          Intelligence.

          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)

          - Face mask detection using a single convolutional neural network.


          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: My academic record
          url: https://example.com
      - title: High School
        school:
          name: Thomas Jefferson High School for Science and Technology.
          url: https://example.org
        GPA: 4.2 out of 5.0
        featuredLink:
          enable: true
          url: https://example.com
  theme:
    disableThemeToggle: true
    defaultTheme: light
  experience:
    enable: false
    items:
      - job: Senior Software Developer
        company: Facebook
        companyUrl: https://example.com
        date: Jan 2022 - present
        featuredLink:
          enable: true
          name: View the project
          url: https://example.com
        content: I am currently working as a software developer at [example
          org.](https://example.com) in San Francisco, CA. I am currently
          working on a project that will be used to help people find the best
          way to get around the city.
  about:
    enable: false
    title: About Me
    image: /images/me.png
    content: >-
      I am a software developer with a passion for web development. I have a
      background in computer science and mathematics, and I have a strong
      interest in the intersection of technology and art. I am currently working
      as a software developer at [example org.](https://example.com) in San
      Francisco, CA.


      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - HTML
        - CSS
        - JavaScript
        - React
        - Node
        - Express
  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
  navbar:
    align: ms-auto
    brandName: Estética Cleopatra
    disableSearch: true
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true
  favicon: /images/fav.png
  title: Estética Cleopatra
  mathjax: false
  projects:
    enable: true
    title: Servicios
    items:
      - title: Trilaser
        content: El mejor equipo de depilación con láser.
        image: https://res.cloudinary.com/dny1bgulo/image/upload/v1725421141/trilaser_m6a9a7.jpg
        featured:
          name: Información
          link: https://example.com
      - title: Paquete Facial Nefertiti
        content: |-
          5 tratamientos faciales con Diatermia.
           Ideal para pieles maduras.
        image: https://res.cloudinary.com/dny1bgulo/image/upload/v1725421141/paquete_nefertiti_zwwhqw.jpg
        featured:
          name: Información
          link: https://example.com
          price: 55,000
      - title: Paquete Facial Cleopatra"
        content: |-
          5 tratamientos faciales con Diatermia y Carboxiterapia.
           Ideal para pieles maduras.
        image: https://res.cloudinary.com/dny1bgulo/image/upload/v1725421141/paquete_cleopatra_vxsmqn.jpg
        featured:
          name: Información
          link: https://example.com
          price: 18,000
  hero:
    enable: true
    logo: https://res.cloudinary.com/dny1bgulo/image/upload/v1725421141/logo_goxssf.png
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-whatsapp fa-bounce
          url: https://wa.me/50685178431
        - icon: fa-regular fa-envelope fa-bounce
          url: mailto:info@cleopatraestetica.com
    roundImage: false
    bottomImage:
      enable: true
    button:
      enable: true
      name: SOLICITE UNA CITA
      url: /#contact
      download: false
      newPage: false
    subtitle: DESCUBRE TU BELLEZA NATURAL
    roundLogo: true
    image: https://images.unsplash.com/photo-1603274737277-f43f54446c7b?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  footer:
    recentPosts:
      path: /blogs
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      instagram: https://instagram.com
      facebook: https://facebook.com
      email: mailto:info@cleopatraestetica.com
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: min read
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true
  datesFormat:
    article: Jan 2, 2006
    articleList: Jan 2, 2006
    articleRecent: Jan 2, 2006
  description: Text about my cool site
markup:
  goldmark:
    renderer:
      unsafe: true
theme: hugo-business
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS
Menus:
  main:
    - identifier: home
      name: Inicio
      title: home
      url: /
      weight: 1
    - identifier: servicios
      name: Servicios
      title: servicios
      url: /#servicios
      weight: 2
    - identifier: contact
      name: Contacto
      title: contacto
      url: /#contact
      weight: 3
Paginate: 3
title: Estética Cleopatra
projects:
  - title: Paquete Facial Test
    content: Un contenido testing
    image: https://res.cloudinary.com/dny1bgulo/image/fetch/v1725421700/https://res.cloudinary.com/dny1bgulo/image/upload/v1725421141/paquete_cleopatra_vxsmqn.jpg
    featured:
      name: Informacion
      link: https://example.com
      price: "78000"
baseURL: https://cleopatraestetica.netlify.app/
