backend:
  name: git-gateway
  branch: master 
media_folder: static/images
public_folder: /images
collections:
  - name: "servicios"
    label: "Servicio"
    label_singular: "Servicio"
    folder: "content/servicios"
    create: true
    slug: "{{slug}}" # This will be used to create a new file with a unique name based on the slug
    extension: md
    fields:
      - { label: "Imagen", name: "image", widget: "image", required: true }
      - { label: "Título", name: "title", widget: "string", required: true }
      - { label: "Descripción", name: "description", widget: "string"}
      - { label: "Fecha", name: "date", widget: "datetime", default: now }
      - { label: "Cuerpo", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }

commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”
  openAuthoring: '{{message}}'  

publish_mode: simple
media_library:
  name: cloudinary
  config:
    cloud_name: dny1bgulo
    api_key: 968862512396434
site_url: http://cleopatraestetica.com/
display_url: http://cleopatraestetica.com/
#logo_url: https://your-site.com/images/logo.svg
locale: 'es'