backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - label: "Servicios"
    name: "servicios"
    files:
      - label: "Servicios"
        name: "servicios"
        file: "config.yaml"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: 'Título', name: 'title', widget: 'string' }
              - { label: 'Contenido', name: 'content', widget: 'text', default: -| }
              - { label: 'Imagen', name: 'image', widget: 'image' }
              - label: 'Destacado'
                name: 'featured'
                widget: 'object'
                fields:
                  - { label: 'Nombre', name: 'name', widget: 'string', default: 'Información' }
                  - { label: 'Enlace', name: 'link', widget: 'string', default: 'https://example.com' }
                  - { label: 'Precio', name: 'price', widget: 'string', required: false }


commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”
  openAuthoring: '{{message}}'  

publish_mode: simple
media_library:
  name: cloudinary
  config:
    cloud_name: dny1bgulo
    api_key: 968862512396434
